version: '3.3'

services:
  db:
    container_name: mysql_db
    image: mysql:latest # After 8.0.26
    ports:
      - '3306:3306'
    env_file: .env
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - codal_network

  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/codal
    ports:
      - "80:8000"
    depends_on:
      - db
      - redis
    links:
      - db

  redis:
    container_name: redis
    image: bitnami/redis:latest # After 6.0.15
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  celery:
    build: .
    command: celery -A codal worker -l info -P solo --logfile=celery.log # Command used to start the Celery worker in the Docker container
    volumes:
      - .:/codal
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      # depends on show that celery worker service requires the web service and the redis service to run
    depends_on:
      - web
      - redis


networks:
  codal_network:
    external: true
