version: '3.3'

services:
  db:
    container_name: mysql_db
    image: mysql:latest # After 8.0.26
    ports:
      - '3306:3306'
    env_file: .env
    volumes:
      - codal_db_volume:/var/lib/mysql
    networks:
      - codal_network

#  web:
#    container_name: web
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/codal
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    links:
#      - db

  redis:
    container_name: redis
    image: bitnami/redis:latest # After 6.0.15
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
    - "6379:6379"  # TODO Delete When Web Created


volumes:
  codal_db_volume:
    external: true

networks:
  codal_network:
    external: true
