#!/bin/sh


for i in {1..50};
do
    /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -d master -i /scripts/init.sql
    if [ $? -eq 0 ]
    then
        echo "SQL database initiation completed"
        break
    else
        echo "not ready yet..."
        sleep 5
    fi
done
